[build]
  command = ""
  publish = "dist"

[[redirects]]
  from = "https://ezydrag.in/*"
  to = "https://ezydrag.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ezydrag.in/*"
  to = "https://ezydrag.com/:splat"
  status = 301
  force = true
